name = "crl-worker"
main = "src/index.js"
compatibility_date = "2024-09-01"



[[kv_namespaces]]
binding = "CRL_NAMESPACE"
id = "<YOUR_KV_NAMESPACE_ID>"


[observability]
enabled = true


[[routes]]
pattern = "<URI_PATH>"
zone_name = "<ZONE_ID>"